title: BloxStreet Newsletters
url: "https://ser0ton1xn.github.io/bloxstreetnewsletter/"
description: A hub for BloxStreet Newsletters.  

back_to_top: true
back_to_top_text: "Back to top" 

aux_links:
  "Group": 
  - "https://www.roblox.com/groups/2700627/Target-Store#!/about" 
  "Store":
  - "https://www.roblox.com/games/539960592/BloxStreet-Shopping"  
  "Support Website": 
  - "https://support.bloxstreet.store/" 
  "Discord Server": 
  - "https://discord.gg/bloxstreet" 
  
aux_links_new_tab: true

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs

search_enabled: true
search: 
